export const cells = {
    cells: [
        { id: 0, name: "Старт", img: "./imgs/cards/secondary/start.png", type: "start", subtype: 'side', class: 'side cell', row: 1, column: 1, players: [{match_id: 0, color: '#69ff6d'}, {match_id: 1, color: "#5a53e0"}, {match_id: 2, color: "#b63040"},{match_id: 3, color: "#bd40aa"},{match_id: 4, color: "#fef685"}, {match_id: 5, color: "#30c0cd"}],},
        { id: 1, name: "S7", img:"./imgs/cards/property/s7.png", color: "#ebc844", type: "property", subtype: 'company', class: 'top cell', row: 1, column: 2,  setName: 'Авикомпания', players: [],owner: {}, houseCount: 0, colorId: 1, price: 60, rent: 2, rentWith1House: 10, rentWith2Houses: 30, rentWith3Houses: 90, rentWith4Houses: 160, rentWithHotel: 250, buildingCost: 50, mortgageValue: 30 },
        { id: 2, name: "Газ", img:"./imgs/cards/property/gas.png", type: "property", subtype: 'communal', class: 'top cell', row: 1, column: 3, color: "#107895", setName: 'Коммунальный услуги', players: [], owner: {}, colorId: 10, price: 100},
        { id: 3, name: "Аэрофлот", img:"./imgs/cards/property/airflot.png", color: "#ebc844", type: "property", subtype: 'company', class: 'top cell', row: 1, column: 4, setName: 'Авикомпания', players: [], owner: {}, houseCount: 0, colorId: 1, price: 60, rent: 4, rentWith1House: 20, rentWith2Houses: 60, rentWith3Houses: 180, rentWith4Houses: 320, rentWithHotel: 450, buildingCost: 50, mortgageValue: 30 },
        { id: 4, name: "Шанс", img:"./imgs/cards/secondary/question.png", type: "chance", subtype: '', class: 'top cell', row: 1, column: 5, players: [],},
        { id: 5, name: "Деньги", img:"./imgs/cards/secondary/money.png", type: "money", class: 'top cell', total: 100, row: 1, column: 6, players: [],},
        { id: 6, name: "Кинопоиск", img:"./imgs/cards/property/kinopoisk.png", color: "#c2561a", type: "property", subtype: 'company', class: 'top cell', row: 1, column: 7, setName: 'Онлайн-кинотеатр', players: [], owner: {}, houseCount: 0, colorId: 2, price: 100, rent: 6, rentWith1House: 30, rentWith2Houses: 90, rentWith3Houses: 270, rentWith4Houses: 400, rentWithHotel: 550, buildingCost: 50, mortgageValue: 50 },
        { id: 7, name: "РЖД", img:"./imgs/cards/property/rzd.png", type: "property", subtype: 'rzd', class: 'top cell', row: 1, column: 8, color: "#bba036", setName: 'ЖД станция',  players: [], owner: {}, propertyCount: 0, colorId: 9, price: 200, rent: 50},
        { id: 8, name: "IVI", img:"./imgs/cards/property/ivi.png", color: "#c2561a", type: "property", subtype: 'company', class: 'top cell', row: 1, column: 9, setName: 'Онлайн-кинотеатр', players: [], owner: {}, houseCount: 0, colorId: 2, price: 100, rent: 6, rentWith1House: 30, rentWith2Houses: 90, rentWith3Houses: 270, rentWith4Houses: 400, rentWithHotel: 550, buildingCost: 50, mortgageValue: 50 },
        { id: 9, name: "OKKO", img:"./imgs/cards/property/okko.png", color: "#c2561a", type: "property", subtype: 'company', class: 'top cell', row: 1, column: 10, setName: 'Онлайн-кинотеатр',  players: [], owner: {}, houseCount: 0, colorId: 2, price: 120, rent: 8, rentWith1House: 40, rentWith2Houses: 100, rentWith3Houses: 300, rentWith4Houses: 450, rentWithHotel: 600, buildingCost: 50, mortgageValue: 60 },
        { id: 10, name: "Тюрьма", img:"./imgs/cards/secondary/jail.png", type: "jail", subtype: 'side', class: 'side cell', row: 1, column: 11, players: [],},
        { id: 11, name: "Перекресток", img:"./imgs/cards/property/prst.png", color: "#829254", type: "property", subtype: 'company', class: 'right cell', row: 2, column: 11, setName: 'Магазин продуктов', players: [], owner: {}, houseCount: 0, colorId: 3, price: 140, rent: 10, rentWith1House: 50, rentWith2Houses: 150, rentWith3Houses: 450, rentWith4Houses: 625, rentWithHotel: 750, buildingCost: 100, mortgageValue: 70 },
        { id: 12, name: "Электричество", img:"./imgs/cards/property/light.png", type: "property", subtype: 'communal', class: 'right cell', row: 3, column: 11, color: "#107895", setName: 'Коммунальный услуги', players: [], owner: {}, colorId: 10, price: 100},
        { id: 13, name: "Магнит", img:"./imgs/cards/property/magnit.png", color: "#829254", type: "property", subtype: 'company', class: 'right cell', row: 4, column: 11, setName: 'Магазин продуктов', players: [], owner: {}, houseCount: 0, colorId: 3, price: 140, rent: 10, rentWith1House: 50, rentWith2Houses: 150, rentWith3Houses: 450, rentWith4Houses: 625, rentWithHotel: 750, buildingCost: 100, mortgageValue: 70 },
        { id: 14, name: "Пятерочка", img:"./imgs/cards/property/pyaterochka.png", color: "#829254", type: "property", subtype: 'company', class: 'right cell', row: 5, column: 11, setName: 'Магазин продуктов', players: [], owner: {}, houseCount: 0, colorId: 3, price: 160, rent: 12, rentWith1House: 60, rentWith2Houses: 180, rentWith3Houses: 500, rentWith4Houses: 700, rentWithHotel: 900, buildingCost: 100, mortgageValue: 80 },
        { id: 15, name: "Казна", img:"./imgs/cards/secondary/chest.png", type: "chest", class: 'right cell', subtype: '', row: 6, column: 11, players: [],},
        { id: 16, name: "Газпром", img:"./imgs/cards/property/gazprom.png", color: "#1395ba", type: "property", subtype: 'company', class: 'right cell', row: 7, column: 11, setName: 'Ресурсы', players: [], owner: {}, houseCount: 0, colorId: 4, price: 180, rent: 14, rentWith1House: 70, rentWith2Houses: 200, rentWith3Houses: 550, rentWith4Houses: 750, rentWithHotel: 950, buildingCost: 100, mortgageValue: 90 },
        { id: 17, name: "РЖД", img:"./imgs/cards/property/rzd.png", type: "property", subtype: 'rzd', class: 'right cell', row: 8, column: 11, color: "#bba036", setName: 'ЖД станция', players: [], owner: {}, propertyCount: 0, colorId: 9, price: 200, rent: 50},
        { id: 18, name: "Лукоил", img:"./imgs/cards/property/lukoil.png", color: "#1395ba", type: "property", subtype: 'company', class: 'right cell', row: 9, column: 11, setName: 'Ресурсы', players: [], owner: {}, houseCount: 0, colorId: 4, price: 180, rent: 14, rentWith1House: 70, rentWith2Houses: 200, rentWith3Houses: 550, rentWith4Houses: 750, rentWithHotel: 950, buildingCost: 100, mortgageValue: 90 },
        { id: 19, name: "Роснефть", img:"./imgs/cards/property/rosneft.png", color: "#1395ba", type: "property", subtype: 'company', class: 'right cell', row: 10, column: 11, setName: 'Ресурсы', players: [], owner: {}, houseCount: 0, colorId: 4, price: 200, rent: 16, rentWith1House: 80, rentWith2Houses: 220, rentWith3Houses: 600, rentWith4Houses: 800, rentWithHotel: 1000, buildingCost: 100, mortgageValue: 100 },
        { id: 20, name: "Парковка", img: "./imgs/cards/secondary/parking.png", type: "parking", subtype: 'side', class: 'side cell', row: 11, column: 11, players: [],},
        { id: 21, name: "Яндекс", img:"./imgs/cards/property/yandex.png", color: "#da611e", type: "property", subtype: 'company', class: 'bottom cell', row: 11, column: 10, setName: 'IT-компания', players: [], owner: {}, houseCount: 0, colorId: 5, price: 220, rent: 18, rentWith1House: 90, rentWith2Houses: 250, rentWith3Houses: 700, rentWith4Houses: 875, rentWithHotel: 1050, buildingCost: 150, mortgageValue: 110 },
        { id: 22, name: "Казна", img:"./imgs/cards/secondary/chest.png", type: "chest", subtype: '', class: 'bottom cell', row: 11, column: 9, players: [],},
        { id: 23, name: "VK", img:"./imgs/cards/property/vk.png", color: "#da611e", type: "property", subtype: 'company', class: 'bottom cell', row: 11, column: 8, setName: 'IT-компания', players: [], owner: {}, houseCount: 0, colorId: 5, price: 220, rent: 18, rentWith1House: 90, rentWith2Houses: 250, rentWith3Houses: 700, rentWith4Houses: 875, rentWithHotel: 1050, buildingCost: 150, mortgageValue: 110 },
        { id: 24, name: "mail.ru", img:"./imgs/cards/property/mailru.png", color: "#da611e", type: "property", subtype: 'company', class: 'bottom cell', row: 11, column: 7, setName: 'IT-компания', players: [], owner: {}, houseCount: 0, colorId: 5, price: 240, rent: 20, rentWith1House: 100, rentWith2Houses: 300, rentWith3Houses: 750, rentWith4Houses: 925, rentWithHotel: 1100, buildingCost: 150, mortgageValue: 120 },
        { id: 25, name: "Водоснабжение", img:"./imgs/cards/property/water.png", type: "property", subtype: 'communal', class: 'bottom cell', row: 11, column: 6, color: "#107895", setName: 'Коммунальный услуги', players: [], owner: {}, colorId: 10, price: 100},
        { id: 26, name: "Сбербанк", img:"./imgs/cards/property/sber.png", color: "#cd5849", type: "property", subtype: 'company', class: 'bottom cell', row: 11, column: 5, setName: 'Банк', players: [], owner: {}, houseCount: 0, colorId: 6, price: 260, rent: 22, rentWith1House: 110, rentWith2Houses: 330, rentWith3Houses: 800, rentWith4Houses: 975, rentWithHotel: 1150, buildingCost: 150, mortgageValue: 130 },
        { id: 27, name: "Тинькоф", img:"./imgs/cards/property/tinkof.png", color: "#cd5849", type: "property", subtype: 'company', class: 'bottom cell', row: 11, column: 4, setName: 'Банк', players: [], owner: {}, houseCount: 0, colorId: 6, price: 260, rent: 22, rentWith1House: 110, rentWith2Houses: 330, rentWith3Houses: 800, rentWith4Houses: 975, rentWithHotel: 1150, buildingCost: 150, mortgageValue: 130 },
        { id: 28, name: "Шанс", img:"./imgs/cards/secondary/question.png", type: "chance", subtype: '', class: 'bottom cell', row: 11, column: 3, players: [],},
        { id: 29, name: "Альфа банк", img:"./imgs/cards/property/alfa.png", color: "#cd5849", type: "property", subtype: 'company', class: 'bottom cell', row: 11, column: 2, setName: 'Банк', players: [], owner: {}, houseCount: 0, colorId: 6, price: 280, rent: 24, rentWith1House: 120, rentWith2Houses: 360, rentWith3Houses: 850, rentWith4Houses: 1025, rentWithHotel: 1200, buildingCost: 150, mortgageValue: 140 },
        { id: 30, name: "Полицейский участок", img: "./imgs/cards/secondary/police.png", type: "police", subtype: 'side', class: 'side cell', row: 11, column: 1, players: [],},
        { id: 31, name: "Lamoda", img:"./imgs/cards/property/lamoda.png", color: "#3a6378", type: "property", subtype: 'company', class: 'left cell', row: 10, column: 1, setName: 'Онлайн-магазин', players: [], owner: {}, houseCount: 0, colorId: 7, price: 300, rent: 26, rentWith1House: 130, rentWith2Houses: 390, rentWith3Houses: 900, rentWith4Houses: 1100, rentWithHotel: 1275, buildingCost: 200, mortgageValue: 150 },
        { id: 32, name: "Wildberries", img:"./imgs/cards/property/wildberries.png", color: "#3a6378", type: "property", subtype: 'company', class: 'left cell', row: 9, column: 1, setName: 'Онлайн-магазин', players: [], owner: {}, houseCount: 0, colorId: 7, price: 300, rent: 26, rentWith1House: 130, rentWith2Houses: 390, rentWith3Houses: 900, rentWith4Houses: 1100, rentWithHotel: 1275, buildingCost: 200, mortgageValue: 150 },
        { id: 33, name: "Деньги", img:"./imgs/cards/secondary/money.png", type: "money", subtype: '', class: 'left cell', row: 8, column: 1, total: 100, players: [],},
        { id: 34, name: "OZON", img:"./imgs/cards/property/ozon.png", color: "#3a6378", type: "property", subtype: 'company', class: 'left cell', row: 7, column: 1, setName: 'Онлайн-магазин', players: [], owner: {}, houseCount: 0, colorId: 7, price: 320, rent: 28, rentWith1House: 150, rentWith2Houses: 450, rentWith3Houses: 1000, rentWith4Houses: 1200, rentWithHotel: 1400, buildingCost: 200, mortgageValue: 160 },
        { id: 35, name: "Шанс", img:"./imgs/cards/secondary/question.png", type: "chance", subtype: '', class: 'left cell', row: 6, column: 1, players: [],},
        { id: 36, name: "РЖД", img:"./imgs/cards/property/rzd.png", type: "property", subtype: 'rzd', class: 'left cell', row: 5, column: 1, color: "#bba036", setName: 'ЖД станция', players: [], owner: {}, propertyCount: 0, colorId: 9, price: 200, rent: 50},
        { id: 37, name: "TELE2", img:"./imgs/cards/property/tele2.png", color: "#cd5849", type: "property", subtype: 'company', class: 'left cell', row: 4, column: 1, setName: 'Сотовый оператор', players: [], owner: {}, houseCount: 0, colorId: 8, price: 350, rent: 35, rentWith1House: 175, rentWith2Houses: 500, rentWith3Houses: 1100, rentWith4Houses: 1300, rentWithHotel: 1500, buildingCost: 200, mortgageValue: 175 },
        { id: 38, name: "Казна", img:"./imgs/cards/secondary/chest.png", type: "chest", subtype: '', class: 'left cell', row: 3, column: 1, players: [],},
        { id: 39, name: "МТС", img:"./imgs/cards/property/mts.png", color: "#cd5849", subtype: 'company', type: "property", class: 'left cell', row: 2, column: 1, setName: 'Сотовый оператор', players: [], owner: {}, houseCount: 0, colorId: 8, price: 400, rent: 50, rentWith1House: 200, rentWith2Houses: 600, rentWith3Houses: 1400, rentWith4Houses: 1700, rentWithHotel: 2000, buildingCost: 200, mortgageValue: 200 },
    ]
};

export const players = {
    count: 6,
    players: [
      {name: 'player', img: "./imgs/player_2.png", id: 1, match_id: 0, money: 2000, monopolies: [], properties: [], color: '#69ff6d', state: 'idle', cell_id: 0},
      {name: 'player2', img: "./imgs/player_2.png", id: 2, match_id: 1, money: 2000, monopolies: [], properties: [], color: '#5a53e0', state: 'idle', cell_id: 0},
      {name: 'player3', img: "./imgs/player_2.png", id: 3, match_id: 2, money: 2000, monopolies: [], properties: [], color: '#b63040', state: 'idle', cell_id: 0},
      {name: 'player4', img: "./imgs/player_2.png", id: 4, match_id: 3, money: 2000, monopolies: [], properties: [], color: '#bd40aa', state: 'idle', cell_id: 0},
      {name: 'player5', img: "./imgs/player_2.png", id: 5, match_id: 4, money: 2000, monopolies: [], properties: [], color: '#fef685', state: 'idle', cell_id: 0},
      {name: 'player6', img: "./imgs/player_2.png", id: 13, match_id: 5, money: 2000, monopolies: [], properties: [], color: '#30c0cd', state: 'roll', cell_id: 0},
    ]
  } 

export const currentPlayer = {name: 'player6', img: "./imgs/player_2.png", id: 13, match_id: 5, money: 10000, monopolies: [], properties: [], color: '#30c0cd', state: 'roll', cell_id: 0}
  